name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and deploy static app
        run: |
          # You can leave this section empty or adjust for Python-specific tasks

      - name: Start Flask application
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=production
          pip install gunicorn
          gunicorn -b 0.0.0.0:5000 app:app
