name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install Python dependencies from requirements.txt

      - name: Build and deploy static app
        run: |
          # If you have any specific build commands for your frontend or static assets, include them here
          # For example, if you need to build CSS or JS assets
          # npm install
          # npm run build

      - name: Start Flask application
        run: |
          cd $GITHUB_WORKSPACE  # Navigate to the root of your repository
          export FLASK_APP=app.py
          export FLASK_ENV=production
          pip install gunicorn  # Install Gunicorn as a production WSGI server
          gunicorn -b 0.0.0.0:5000 app:app  # Replace 'app:app' with your Flask application entry point
